# build site
FROM python:3.9 as dbt_site_builder

COPY source/profiles/big_query/profiles.yml ./root/.dbt/profiles.yml
COPY source/dbt_project_prod.yml source/dbt_project.yml
# here add the environment variables you need and will pass via --build-arg 
# ARG ...  

# install dbt
ENV DBT_VERSION=1.0.0
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y -q \
    git libpq-dev python-dev

RUN apt-get update -y && \
    apt-get upgrade -y && \
	apt-get install openssh-server -y && \
	apt-get install sshpass -y

# Set environment variables and working directory
ENV DBT_DIR /source
COPY . .
WORKDIR $DBT_DIR
ENV DBT_PROFILES_DIR $DBT_DIR/profiles/big_query/

# BigQuery
# ENV GOOGLE_APPLICATION_CREDENTIALS ./resources/service-account.json

# Python Dépendancy
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


# pull dbt dependencies
RUN dbt deps

# build static pages
RUN dbt debug
RUN dbt docs generate
# RUN dbt run
ENTRYPOINT [ "dbt"]

# # serve site
# FROM nginx:stable-alpine

# # here copy any nginx related files you might need for your deployment, for example nginx.conf
# # ADD ...
# RUN apk add --no-cache bash
# COPY --from=dbt_site_builder /source/target/index.html /source/target/manifest.json /source/target/catalog.json /source/target/run_results.json /usr/share/nginx/html/

